Added option to reboot to payload
rdmrocha/linkalho pull request #1
Opened 2020-09-15 13:36 UTC by HamletDuFromage

Absolutely love this homebrew. I tried writing it a few months ago but was too dumb to succeed.

I added an automatic reboot to payload (which turns off the console like before off if it fails) to not have to go look for a jig and/or acable.

I tested it with Atmosphere, it should also work fine with ReiNX and probably with SXOS too but I haven't tested those two. The code mostly comes from Atmosphere, and I took the vain liberty to credit myself in the README, but you're free to remove it of course, I barely did anything anyway.

Hope you like it!

2020-09-15 14:42 UTC, rdmrocha requested changes
Thanks for this. I'm a SXOS user myself so I'll give it a spin once later tonight. Code looks simple and efective. I'll just make sure it works well for my case (since you already tested with atmos). It would be great to get someone to test it with ReiNX too but assuming the reboot to payload is pretty much a well tested code from SciresM, it should work fine. I'll leave you with just a couple of change request (nitpicks) for the sake of code organisation a consistency. 

Thanks again

2020-09-15 14:42 UTC, rdmrocha commented on include/reboot_payload.h
> +#ifndef __REBBOT_PAYLOAD_H__
nitpick to the extreme but the **_REBBOT_** -> **_REBOOT_** typo trigger my OCD :D

2020-09-15 14:42 UTC, rdmrocha commented on include/reboot_payload.h
> +enum CFW{
can we get the enum, is_service_sunning and get_CFW into the utils for the sake of organisation? since they are not an integral part of the "reboot to payload" core code? Thanks

2020-09-15 14:42 UTC, rdmrocha commented on src/reboot_payload.c
> +                f = fopen("sdmc:/atmosphere/reboot_payload.bin", "rb");
for consistency sake, can we move the constants to **constants.hpp**? Thanks

2020-09-15 16:22 UTC, HamletDuFromage commented on src/reboot_payload.c
> +                f = fopen("sdmc:/atmosphere/reboot_payload.bin", "rb");
Done

2020-09-17 00:02 UTC, rdmrocha commented
Hey mate. I got some time to read the code and test it. As expected, it does not work with SXOS, as boot.dat is a second stage payload. In order for it to work, I'd have to include Xecuter's payload.bin which is something I won't due for obvious reasons. Give this, I won't merge the PR but feel free to incorporate the changes in your build and use it or even distribute it.

Thanks

2020-09-17 00:02 UTC, closed without merging

2020-09-17 00:15 UTC, HamletDuFromage commented
I guess you could make it so that it reboots for SXOS and reboots to payload for the rest, but considering that you wouldn't realistically use that app more than once or twice, maybe there's no point in it.
Anywho, thanks for the app still!